name: osshs
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - aiobotocore=2.1.0
  - aiohttp=3.8.1
  - aioitertools=0.10.0
  - aiosignal=1.2.0
  - alembic=1.7.7
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=3.0.0
  - async-timeout=4.0.2
  - atk-1.0=2.36.0
  - atpublic=3.0.1
  - attrs=21.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.10.0
  - bitarray=2.3.4
  - bleach=4.1.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - boost-cpp=1.68.0
  - botocore=1.23.24
  - bottleneck=1.3.2
  - branca=0.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bs4=4.10.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.2.1
  - cached_property=1.5.2
  - cachetools=5.0.0
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=3.470
  - charset-normalizer=2.0.9
  - click=7.1.2
  - click-plugins=1.1.1
  - clickhouse-cityhash=1.0.2.3
  - clickhouse-driver=0.2.2
  - clickhouse-sqlalchemy=0.1.7
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=36.0.1
  - curl=7.80.0
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask=2021.10.0
  - dask-core=2021.10.0
  - datafusion=0.4.0
  - decorator=4.4.2
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - distributed=2021.10.0
  - docopt=0.6.2
  - double-conversion=3.1.7
  - edn_format=0.7.5
  - entrypoints=0.3
  - expat=2.4.2
  - fastavro=1.4.8
  - fiona=1.8.13.post1
  - flit-core=3.6.0
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.28.5
  - freetype=2.10.4
  - freexl=1.0.6
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - fsspec=2022.2.0
  - gdal=3.0.2
  - gdk-pixbuf=2.42.6
  - geoalchemy2=0.6.3
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geos=3.8.0
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - glog=0.5.0
  - gobject-introspection=1.56.1
  - google-api-core=2.5.0
  - google-api-core-grpc=2.5.0
  - google-auth=2.6.0
  - google-cloud-bigquery=2.34.1
  - google-cloud-bigquery-core=2.34.1
  - google-cloud-bigquery-storage-core=2.11.0
  - google-cloud-core=2.2.2
  - google-crc32c=1.1.2
  - google-resumable-media=2.1.0
  - googleapis-common-protos=1.54.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpc-cpp=1.39.0
  - grpcio=1.44.0
  - grpcio-status=1.41.1
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=3.1.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - ibis-framework=2.1.1
  - ibis-framework-core=2.1.1
  - icu=58.2
  - idna=3.1
  - importlib-metadata=4.10.1
  - importlib_resources=5.4.0
  - impyla=0.17.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.3
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9d
  - json-c=0.13.1
  - jsonschema=4.4.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcst=0.4.1
  - libcurl=7.80.0
  - libdap4=3.19.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgdal=3.0.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.6.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.17.2
  - librsvg=2.52.5
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.14.2
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libwebp-base=1.2.1
  - libxcb=1.14
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzlib=1.2.11
  - locket=0.2.1
  - lxml=4.8.0
  - lz4=3.1.10
  - lz4-c=1.9.3
  - lzo=2.10
  - mako=1.2.0
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - mistune=0.8.4
  - mock=4.0.3
  - msgpack-python=1.0.3
  - multidict=6.0.2
  - multipledispatch=0.6.0
  - munch=2.5.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclient=0.5.10
  - nbconvert=6.4.1
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - networkx=2.6.3
  - ninja=1.10.1
  - nomkl=1.0
  - notebook=6.4.8
  - numexpr=2.8.0
  - numpy=1.21.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1m
  - orc=1.6.9
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - pango=1.48.10
  - parso=0.8.0
  - parsy=1.3.0
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.2.4
  - pixman=0.40.0
  - ply=3.11
  - poppler=0.89.0
  - poppler-data=0.4.11
  - postgresql=12.9
  - proj=6.2.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.8
  - proto-plus=1.19.6
  - protobuf=3.17.2
  - psutil=5.9.0
  - psycopg2=2.8.6
  - ptyprocess=0.6.0
  - pure-sasl=0.6.2
  - py4j=0.10.9.2
  - pyarrow=3.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygithub=1.55
  - pygments=2.7.1
  - pyjwt=2.3.0
  - pykerberos=1.2.1
  - pymysql=1.0.2
  - pynacl=1.5.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyproj=2.6.1.post1
  - pyrfc3339=1.1
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - pyspark=3.2.0
  - pytables=3.6.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-dotenv=0.19.2
  - python-graphviz=0.19.1
  - python-hdfs=2.6.0
  - python-tzdata=2021.5
  - python_abi=3.8
  - pytz=2021.3
  - pytz-deprecation-shim=0.1.0.post0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=19.0.2
  - re2=2021.11.01
  - readline=8.1
  - regex=2021.11.10
  - requests=2.26.0
  - requests-kerberos=0.12.0
  - rsa=4.8
  - rtree=0.9.7
  - s3fs=2022.2.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=60.1.0
  - shapely=1.7.1
  - six=1.16.0
  - snappy=1.1.8
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sqlalchemy=1.3.23
  - sqlite=3.37.0
  - tblib=1.7.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - thrift=0.15.0
  - thrift_sasl=0.4.3
  - thriftpy2=0.4.14
  - tiledb=2.2.9
  - tk=8.6.11
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.0.5
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - typing_inspect=0.7.1
  - tzdata=2021e
  - tzlocal=4.1
  - unicodedata2=14.0.0
  - uriparser=0.9.5
  - urllib3=1.26.7
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - wrapt=1.13.3
  - xerces-c=3.2.3
  - xyzservices=2021.11.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.3
  - zict=2.1.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - filelock==3.6.0
    - huggingface-hub==0.4.0
    - iniconfig==1.1.1
    - nltk==3.7
    - pluggy==1.0.0
    - py==1.11.0
    - pytest==6.2.5
    - ray
    - sacremoses==0.0.49
    - sentence-transformers==2.2.0
    - sentencepiece==0.1.96
    - tokenizers==0.11.6
    - toml==0.10.2
    - torch==1.11.0
    - torchvision==0.12.0
    - transformers==4.17.0
