name: governance
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.2
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.3
  - executing=0.8.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.1.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - libcxx=12.0.0
  - libffi=3.3
  - libsodium=1.0.18
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - numexpr=2.8.1
  - numpy-base=1.21.2
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.4.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.2
  - stack_data=0.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - pip:
    - attrs==21.4.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - commonmark==0.9.1
    - deprecated==1.2.13
    - filelock==3.6.0
    - huggingface-hub==0.4.0
    - idna==3.3
    - iniconfig==1.1.1
    - joblib==1.1.0
    - keybert==0.5.0
    - nltk==3.7
    - numpy==1.22.3
    - pillow==9.0.1
    - pluggy==1.0.0
    - py==1.11.0
    - pycparser==2.21
    - pygithub==1.55
    - pyjwt==2.3.0
    - pynacl==1.5.0
    - pyparsing==3.0.7
    - pytest==7.0.1
    - python-dotenv==0.19.2
    - pyyaml==6.0
    - regex==2022.3.2
    - requests==2.27.1
    - rich==12.0.0
    - sacremoses==0.0.47
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - sentence-transformers==2.2.0
    - sentencepiece==0.1.96
    - threadpoolctl==3.1.0
    - tokenizers==0.11.6
    - tomli==2.0.1
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.63.0
    - transformers==4.17.0
    - typing-extensions==4.1.1
    - urllib3==1.26.8
    - wrapt==1.14.0
